### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by purexo** [uzyn/tag#7]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Théotime\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Théotime\.atom\packages\tag\lib\tag.js:17:16)
```

**Comment by uzyn** [comment]
This issue should be fixed now with v0.3.0.

Please update.
